[package]
name = "hostname"
version = "0.1.3"
description = "Get hostname. Compatible with windows and linux."
keywords = ["hostname", "objectid"]
authors = ["fengcen <fengcen.love@gmail.com>"]
repository = "https://github.com/fengcen/hostname.git"
homepage = "https://github.com/fengcen/hostname"
documentation = "https://docs.rs/hostname"
readme = "README.md"
license = "MIT"

[lib]
name = "hostname"
path = "src/lib.rs"

[features]
unstable = []

[dependencies]
libc = "^0.2"

[target."cfg(windows)".dependencies]
winapi = { version = "~0.3", features = ["sysinfoapi"] }
